<html>
	<head>
		<title>The Next Social</title>
		<!-- Load Twitter Bootstrap and jQuery -->
		<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
	</head>
	<body>
		<div id="site_container">
			<div id="header">
				<p>This is the header!</p>
			</div>
			<div id="content">
				<!-- Echo our content here! -->
				<?php echo $this->layout()->content; ?>
			</div>
			<div id="footer">
				<p>This is the footer!</p>
			</div>
		</div>
	</body>
</html>