<?php

/**
 * Model_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_User');
    }
}