<?php

/**
 * Model_UserSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserSettings');
    }
}